language: node_js
node_js:
  - 10

dist: trusty
sudo: false
cache:
  directories:
  - "$HOME/.npm"

install:
- npm ci

stages:
  - name: test
    if: type = pull_request
  - name: npm deploy
    if: tag =~ /^v?[0-9\\.]+/

jobs:
  include:
    - stage: test
      script: npm run test
    - stage: npm deploy
      before_install: skip
      install: skip
      script: skip
      after_success: true
      deploy:
        provider: npm
        email: $NPM_EMAIL
        api_key: $NPM_TOKEN
        skip_cleanup: true
        on:
          tags: true
